name: MiniPlaceholders-LuckPerms
version: '${version}'
author: 4drian3d
main: io.github.miniplaceholders.expansion.luckperms.paper.PaperPlugin
api-version: '1.19'
folia-supported: false
dependencies:
  - name: MiniPlaceholders
    required: true
  - name: LuckPerms
    required: true
